name: Publish to Artifact Hub

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/artifacthub.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm chart
        run: |
          helm package charts/web-load-tester
          helm repo index .

      - name: Publish to Artifact Hub
        env:
          AH_API_KEY: lUp8P9QPOLAd0mrm7epiaK/ApcmmMLA9p2mNymRvbDE=
        run: |
          curl -X POST \
            -H "X-API-KEY: $AH_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "k6-load-tester",
              "displayName": "K6 Load Tester",
              "url": "https://github.com/hjali7/k6-load-tester",
              "kind": "helm",
              "private": false,
              "verifiedPublisher": false,
              "organizationName": "hjali7",
              "organizationDisplayName": "HajAli",
              "userAlias": "hjali7"
            }' \
            https://artifacthub.io/api/v1/repositories 