name: Publish to Artifact Hub

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/artifacthub.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      - name: Run Artifact Hub Publisher
        uses: artifacthub/artifacthub-publisher@v1
        with:
          ah_api_key: ${{ secrets.ARTIFACT_HUB_API_KEY }}
          ah_repo_name: k6-load-tester
          ah_repo_kind: helm
          ah_repo_url: https://github.com/hjali7/k6-load-tester
          ah_repo_private: false
          ah_repo_verified_publisher: false
          ah_repo_organization_name: hjali7
          ah_repo_organization_display_name: HajAli
          ah_repo_user_alias: hjali7 