name: Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, GitHub Actions is working!"

      - name: Run a multi-line script
        run: |
          echo "Testing GitHub Actions"
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la 